CREATE DATABASE INTERNSHIP_DB;
USE INTERNSHIP_DB;

CREATE TABLE EMPLOYEES (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    SALARY FLOAT,
    DEPARTMENT_ID INT
);

INSERT INTO EMPLOYEES VALUES
(1, 'AMIT', 30000, 2),
(2, 'NEHA', 40000, 3),
(3, 'RAVI', 25000, 2),
(4, 'SIMRAN', 35000, 3),
(5, 'ANIL', 28000, 1);

-- PROCEDURE CREATION WITH IN AND OUT PARAMETERS:

DELIMITER //

CREATE PROCEDURE DEPT_EMP_COUNT(
    IN DEPT INT,
    OUT TOTAL INT
)
BEGIN
    IF DEPT IS NULL THEN
        SET TOTAL = 0;
    ELSE
        SELECT COUNT(*) INTO TOTAL
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID = DEPT;
    END IF;
END //

DELIMITER ;

-- CALLING A PROCEDURE:
SET @TOTAL = 0; -- USE TO STORE THE VALUE OF OUT PARAMETER
CALL DEPT_EMP_COUNT(2, @TOTAL);
SELECT @TOTAL AS TOTAL_EMPLOYEES;

-- FUNCTION CREATION:

DELIMITER //

CREATE FUNCTION EMP_LEVEL(SALARY FLOAT)
RETURNS VARCHAR(10)
DETERMINISTIC
BEGIN
    IF SALARY < 30000 THEN
        RETURN 'LOW';
    ELSE
        RETURN 'HIGH';
    END IF;
END //

DELIMITER ;

-- USING A FUNCTION:

SELECT EMP_NAME, SALARY, EMP_LEVEL(SALARY) AS LEVEL
FROM EMPLOYEES;
